// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ophtctbhhoqjskfiohjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9waHRjdGJoaG9xanNrZmlvaGp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4MjM5MzQsImV4cCI6MjA4OTM5OTkzNH0.XfRlLaN8x0yo5Zje_rlcu-p3UFbkqKkdMVSgM_zMDMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});